#FROM nginx:latest
#COPY nginx.conf /etc/nginx/nginx.conf

# Nginx 최신 이미지를 사용
FROM nginx:latest

# 작업 디렉토리 설정
WORKDIR /etc/nginx

# 호스트의 nginx.conf 파일을 컨테이너로 복사
COPY nginx.conf /etc/nginx/nginx.conf

# Nginx 설정 파일이 올바르게 복사되었는지 확인하기 위한 로그 출력
RUN echo "Checking if /etc/nginx/nginx.conf exists..."
RUN ls -l /etc/nginx/nginx.conf || echo "/etc/nginx/nginx.conf does not exist"

# Nginx 포트 설정
EXPOSE 80

# Nginx 시작
CMD ["nginx", "-g", "daemon off;"]
