#FROM nginx:latest
#COPY nginx.conf /etc/nginx/nginx.conf
#
## 파일 존재 여부 확인
#RUN echo "Checking if /etc/nginx/nginx.conf exists..."
#RUN ls -l /etc/nginx/nginx.conf || echo "/etc/nginx/nginx.conf does not exist"
